version: "3"
services:
  web:
    container_name: code-server
    image: my-code-server:setting
    restart: always
    ports:
      - "8443:8443"
      - "8080:8080"
    environment:
      - PASSWORD=opennaru
    volumes:
      - /code:/config/workspace
